version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: ./.docker/server/Dockerfile
    ports:
     - "127.0.0.1:3000:3000"
    volumes:
     - ".:/usr/src/app:delegated"
    env_file:
      - ./env/development.env
    command: ["npm", "run", "start:dev"]
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    volumes:
      - "./bin/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:delegated"
      - "simplereminder_pg:/var/lib/postgresql/data:delegated"
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - ./env/development.env

volumes:
  simplereminder_pg:
    external: true