version: '3.4'

services:
  server:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ".:/usr/src/app:delegated"
    env_file:
      - ./env/development.env
    command: ["npm", "run", "start:dev"]
    depends_on:
    - db
  db:
    image: postgres
    volumes:
      - "simple-reminder-postgres:/var/lib/postgresql/data:delegated"
    ports:
      - "0.0.0.0:5432:5432"
    env_file:
      - ./env/development.env

volumes:
  simple-reminder-postgres:
    external: true