version: '3.8'

services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - "simplereminder_pg:/var/lib/postgresql/data:delegated"
    ports:
      - "127.0.0.1:5432:5432"
    environment: 
      - POSTGRES_USER=simplereminder
      - POSTGRES_PASSWORD=admin

  server-dev:
    build: 
      context: .
      target: "develop-stage"
      dockerfile: "./.docker/Dockerfile"
    ports:
     - "127.0.0.1:3000:3000"
    volumes:
     - ".:/usr/src/app:delegated"
    env_file:
      - ./env/development.env
    command: ["npm", "run", "start:dev"]
    depends_on:
      - db

  server:
    build: 
      context: .
      target: "build-stage"
      dockerfile: "./.docker/Dockerfile"
    ports:
      - "127.0.0.1:8081:8081"
    env_file:
      - ./env/production.env
    command: ["npm", "run", "start"]
    depends_on:
      - db

volumes:
  simplereminder_pg:
    external: true